# Generated by Django 3.0.5 on 2020-04-10 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingretiens',
            new_name='ingredients',
        ),
    ]
